package com.github.gameoholic.twitchrewards.Rewards;

public enum RewardType {
    SPAWN_ENTITY, POTION_EFFECT, LAUNCH, DROP_ITEM, DROP_INVENTORY,
    GIVE_ITEM, LOCK_INVENTORY_SLOT, CLUTCH_CHALLENGE, GOD_MODE, FLIGHT, NO_CRAFTING, NO_BREAKING, NO_PLACING,
    ADD_TO_WHITELIST, AIRDROP, TNT_RUN
}
