############################################################
# +------------------------------------------------------+ #
# |               CONFIGURATION                          | #
# +------------------------------------------------------+ #
############################################################

#If you need help setting up the plugin, contact Gameoholic#8987 on Discord

#------------ MANAGING REDEEMS ------------

#Consult the full documentation on how to manage and customize your redeems. Otherwise, you may use
#one of the redeem templates located in the RedeemTemplates folder.

#The first line of each redeem is the redeem's title, and must match the redeem you have on your Twitch channel.
#The current Redeems configuration is below, and you may use it or edit it however you want.

#Don't forget to restart the server after making changes to this file!

#Sound that plays when a redeem is used
Sound: BLOCK_GLASS_BREAK #Sounds here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html

Redeems:
  - Give me a random item: #Redeem's title, must match the one you have on Twitch
      - Reward: GiveItem   #Reward type, this must be one of the values listed in the documentation
      - Item: RANDOM       #For GiveItem, you can either set this to RANDOM or to one of the values listed here:
                           #https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html (for example, DIAMOND_SWORD)
  - Give me a random effect:
      - Reward: PotionEffect
      - Effect: RANDOM
      - Duration: RANDOM
      - Amplifier: RANDOM
  - Spawn a creeper:
      - Reward: SpawnEntity
      - Entity: CREEPER
      - Count: 1
  - Launch:
      - Reward: Launch
      - Velocity: 3
  - Drop item in hand:
      - Reward: DropItem
  - Lock an inventory slot:
      - Reward: LockInventorySlot
      - Time: 30
  - No Placing blocks:
      - Reward: NoPlacing
      - NoPlacingDuration: 30
  - No breaking blocks:
      - Reward: NoBreaking
      - NoBreakingDuration: 30
  - No crafting:
      - Reward: NoCrafting
      - NoCraftingDuration: RANDOM
  - Make Me Clutch:
      - Reward: ClutchChallenge
      - ClutchItem: RANDOM
      - Height: 100
  - Drop everything in my inventory:
      - Reward: DropInventory
  - God Mode:
      - Reward: GodMode
      - GodModeDuration: 3
  - Flight:
      - Reward: Flight
      - FlightDuration: 10