############################################################
# +------------------------------------------------------+ #
# |               CONFIGURATION                          | #
# +------------------------------------------------------+ #
############################################################

#If you need help setting up the plugin, contact Gameoholic#8987 on Discord.

#------------------------------------ GENERAL SETTINGS ------------------------------------

#-Sound that plays when a redeem is used-
Sound: BLOCK_GLASS_BREAK #Sounds here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html

#-Message that gets sent when a redeem is redeemed-
#Color codes here: https://www.digminecraft.com/lists/color_list_pc.php
#Recommended value for one streamer: "&eACTIVATOR_USERNAME activated &bREDEEM_TITLE &efor POINTS points. MESSAGE"
#Recommended value for multiple streamers: "&aSTREAMER_USERNAME: &eACTIVATOR_USERNAME activated &bREDEEM_TITLE &efor POINTS points. MESSAGE"
RedeemMessage: "&aSTREAMER_USERNAME: &eACTIVATOR_USERNAME activated &bREDEEM_TITLE &efor POINTS points. MESSAGE"

#------------------------------------ MANAGING REDEEMS ------------------------------------

#Consult the full documentation on how to manage and customize your redeems:
#https://github.com/Gameoholic/TwitchRewards/wiki/Editing-the-Config-file
#Otherwise, you may use one of the redeem templates located in the RedeemTemplates folder.

#The first line of each redeem is the redeem's title, and must match the redeem you have on your Twitch channel.
#The default Redeems configuration is below, and you may use it or edit it however you want.

#Don't forget to restart the server after making changes to this file!

Redeems:
  - Give me a random item:
      - Reward: GiveItem
      - Item: RANDOM
  - Give me a random effect:
      - Reward: PotionEffect
      - Effect: RANDOM
      - Duration: RANDOM
      - Amplifier: RANDOM
  - Spawn a creeper on me:
      - Reward: SpawnEntity
      - Entity: CREEPER
      - Count: 1
  - Spawn a random mob on me:
      - Reward: SpawnEntity
      - Entity: RANDOM
      - Count: 1
  - Launch me:
      - Reward: Launch
      - Velocity: 3
  - Drop item in hand:
      - Reward: DropItem
  - Remove my item:
      - Reward: RemoveItem
  - Drop everything in my inventory:
      - Reward: DropInventory
  - Lock an inventory slot:
      - Reward: LockInventorySlot
      - Time: 30
  - No Placing blocks:
      - Reward: NoPlacing
      - NoPlacingDuration: 30
  - No breaking blocks:
      - Reward: NoBreaking
      - NoBreakingDuration: 30
  - No crafting:
      - Reward: NoCrafting
      - NoCraftingDuration: RANDOM
  - Make Me Clutch:
      - Reward: ClutchChallenge
      - ClutchItem: RANDOM
      - Height: 100
  - God Mode:
      - Reward: GodMode
      - GodModeDuration: 3
  - Flight:
      - Reward: Flight
      - FlightDuration: 10
  - Spawn Air Drop [Legendary Quality]:
      - Reward: AirDrop
      - AirDropRarity: LEGENDARY
  - Spawn Air Drop [Random]:
      - Reward: AirDrop
      - AirDropRarity: RANDOM
  - Whitelist for 5 minutes:
      - Reward: AddToWhitelist
      - WhitelistDuration: 300
      - TeleportCooldown: 60
  - Activate TNT Run:
      - Reward: TNTRun
      - BlockDisappearDelay: 0.5
      - TNTRunDuration: 60
      - TNTRunRadius: 1
  - Activate Mega TNT Run:
      - Reward: TNTRun
      - BlockDisappearDelay: 0.5
      - TNTRunDuration: 30
      - TNTRunRadius: 2