name: TwitchRewards
version: '${project.version}'
main: com.github.gameoholic.twitchrewards.TwitchRewards
api-version: 1.19
authors: [ Gameoholic ]
description: Twitch Rewards

commands:
  testredeem:
    description: Test a redeem (for debugging purposes)
    usage: /testredeem <redeem name>
  addstreamer:
    description: Adds a streamer
    usage: /addstreamer <streamer username>
  removestreamer:
    description: Removes a streamer
    usage: /removestreamer <streamer username>
  setredeemplayers:
    description: Sets the player/s to be affected by redeems, separate players with spaces
    usage: /setredeemplayers <player username/s>
  setclientid:
    description: Sets the client ID
    usage: /setclientid <client ID>
  setaccesstoken:
    description: Sets the access token
    usage: /setaccesstoken <access token>
  startredeems:
    description: Opens Twitch Client and starts listening to redeems
    usage: /startredeems
  pauseredeems:
    description: Pauses redeems
    usage: /pauseredeems
  redeemsstatus:
    description: Prints status of the Twitch Client
    usage: /redeemstatus
