name: TwitchRewardsPlugin
version: '${project.version}'
main: com.github.gameoholic.twitchrewardsplugin.TwitchRewardsPlugin
api-version: 1.19
authors: [ Gameoholic ]
description: Twitch Rewards

commands:
  testredeem:
    description: Test a redeem (for debugging purposes)
    usage: /testredeem <redeem name>
  setstreamer:
    description: Sets the streamer
    usage: /setstreamer <streamer username>
  setredeemplayer:
    description: Sets the player/s to be affected by redeems, separate players with spaces
    usage: /setredeemplayer <player username/s>
  setclientid:
    description: Sets the client ID
    usage: /setclientid <client ID>
  setaccesstoken:
    description: Sets the access token
    usage: /setaccesstoken <access token>
  startredeems:
    description: Opens Twitch Client and starts listening to redeems
    usage: /startredeems
  pauseredeems:
    description: Pauses redeems
    usage: /pauseredeems
  redeemsstatus:
    description: Prints status of the Twitch Client
    usage: /redeemstatus