package com.github.gameoholic.twitchrewardsplugin.Rewards;

public enum RewardType {
    SPAWN_ENTITY, POTION_EFFECT, LAUNCH, DROP_ITEM, DROP_INVENTORY,
    GIVE_ITEM, LOCK_INVENTORY_SLOT, CLUTCH_CHALLENGE, GOD_MODE, FLIGHT, NO_CRAFTING, NO_BREAKING, NO_PLACING,
    RESET_WORLD, ADD_TO_WHITELIST
}
